### PR TITLE
Fix readinessProbe

### PR DESCRIPTION
**Pull request by schroedermatthias**
Fix copy & paste error

### CODE REVIEW

**Comment by nabeelsaabna** [comment]
Thanks for the PR
can you please update `helm-charts/mend-renovate-ee/templates/server-deployment.yaml` as well
and bump the charts patch version

**Comment by schroedermatthias** [comment]
@nabeelsaabna Sure, good point. How does it work with the appVersion in the Chart.yaml? Should it be increased accordingly to stay in sync with the Chart version?

**Comment by nabeelsaabna** [comment]
It's already out of sync, setting the patch `x.y.0` to `x.y.1` is good enough

**Comment by schroedermatthias** [comment]
@nabeelsaabna  Done :)

**Review by nabeelsaabna — APPROVED** [review]

**Pull request merged**
